//Arrays:

export const index = []

export const chosenfns = []

//Home4LetrasChosen:
export const as4letrasChosenBotao = [
    {pt: "Saiba mais sobre o", en: "See more about the"}
]

export const genericComments = [
  {
  personalityWarning: "\"Classes\" são sobretudo espectros. São sobre aproximação e preponderância e não exatidão. Logo, nem todo indivíduo é um exemplo típico de seu tipo e não necessariamente ressoará inteiramente as descrições \"genéricas\" comumente encontradas na Internet. A complexidade da personalidade humana não pode ser totalmente capturada em apenas alguns parágrafos.",
  majorWarning: "",
  stackWarning: "As duas primeiras funções cognitívas são as mais frequente e intensamente adotadas pelo detentor da personalidade, enquanto a quarta função indica aquela menos forte e mais difícil de se empregar plenamente. Veja mais na sessão \"'Papéis' na personalidade\"",
  comboWarning: "Ao ler uma característica descrita, não diga \"ah, mas todo mundo faz isso\". Certamente todos apresentam certas atitudes ora ou outra, mas a frequencia o conforto e a intensidade com que praticam certas ações em detrimento de outras é o que determina sua personalidade. Alguem também poderia dizer, \"ah, mas ",
  jungWarning: "",
  }
]

export const genericCommentsEnglish = []

export const fnx = [
    {name: "Todos", desc: "Visão geral das Funções Cognitivas", brief: "", long: ""}, 
    {name: "Fe", desc: "Sentimento Extrovertido", brief: "O Sentimento Extrovertido (Fe) é...", long: ""}, 
    {name: "Fi", desc: "Sentimento Introvertido", brief: "O Sentimento Introvertido (Fi) busca a harmonia de ações e pensamentos baseando-se em valores pessoais. Nem sempre articula esses valores, mas busca entender e redimir o outro e o ambiente externo.", long: ""},
    {name: "Te", desc: "Pensamento Extrovertido", brief: "O Pensamento Extrovertido (Te) busca lógica e consistência no mundo à sua volta. Se tange em leis e regras externas. Cria estruturas e reproduz \"razões\" preferencialmente mensuráveis e evidenciáveis.", long: ""},
    {name: "Ti", desc: "Pensamento Introvertido", brief: "O Pensamento Introvertido (Ti) é...", long: ""},
    {name: "Se", desc: "Sensação Extrovertida", brief: "A Sensação Extrovertida (Se) vivencia plenamente e age sobre os dados concretos do aqui e agora. Confia no presente e se move quase sempre com ações tangíveis e relevantes para o contexto atual.", long: ""},
    {name: "Si", desc: "Sensação Introvertido", brief: "A Sensação Introvertida (Si) compara e/ou integra fatos e experênicas presentes com as suas experiências passadas consideradas importantes. Armazena dados e informações sensoriais (sensíveis) para uso futuro.", long: ""},
    {name: "Ne", desc: "Intuição Extrovertida", brief: "A Intuição Extrovertida (Ne) é...", long: ""},
    {name: "Ni", desc: "Intuição Introvertida", brief: "A Intuição Introvertida (Ni) examina a consistência de idéias ou pensamentos através de um arcabouço interno. Confia em 'fashes' vindos do inconsciente, por vezes difíceis de serem entendidos por outros se muito abstratos.", long: ""}
]

export const fnEnglish = []

export const as4letrasx = [
    {name: "Todos", desc: "Todos", f1: "", f2: "", f3: "", f4: "", f5: "", f6: "", f7: "", f8: "", catch: ""}, 
    {name: "ENTP", desc: "adoram emoção e desafio. Entusiasmados e engenhosos, eles são falantes, inteligentes e bons em muitas coisas e constantemente se esforçam para aumentar sua competência e poder pessoal. ENTPs nascem empreendedores. Eles são fascinados por novas ideias e estão atentos a todas as possibilidades. Eles têm forte iniciativa e operam no impulso criativo. Os ENTPs valorizam sua inspiração acima de tudo e se esforçam para transformar suas ideias originais em realidade. Eles são curiosos, versáteis, adaptáveis ​​e engenhosos na resolução de problemas desafiadores e teóricos. Alertas e francos, os ENTPs podem facilmente ver a falha em qualquer posição e muitas vezes gostam de discutir por diversão em ambos os lados de um problema. Eles têm excelentes habilidades analíticas e são grandes pensadores estratégicos. Eles quase sempre podem encontrar uma razão lógica para as coisas que desejam. A maioria dos ENTPs gosta de testar os limites ao seu redor e considera que a maioria das regras e regulamentos devem ser questionados, se não quebrados. Eles às vezes não são convencionais em sua abordagem e gostam de ajudar os outros a superar o que é aceito e esperado. Eles gostam de viver livremente e procuram diversão e variedade em situações cotidianas. ENTPs lidam imaginativamente com as relações sociais e muitas vezes têm um grande número e variedade de amigos e conhecidos. Eles podem exibir grande humor e otimismo. Os ENTPs podem ser uma companhia atrativa e estimulante e muitas vezes inspiram outras pessoas a se envolverem em seus projetos através de seu entusiasmo contagiante. Eles normalmente preferem tentar entender e responder às pessoas em vez de julgá-las.", author: "Barron & Tieger", f1: "Ne", f2: "Ti", f3: "Fe", f4: "Si", f5: "Ni", f6: "Te", f7: "Fi", f8: "Se", catch: "cccccccccc"}, 
    {name: "ENTJ", desc: "são grandes líderes e tomadores de decisão. Eles veem facilmente possibilidades em todas as coisas e ficam felizes em direcionar os outros para tornar sua visão uma realidade. Eles são pensadores engenhosos e grandes planejadores de longo prazo. Como os ENTJs são tão lógicos e analíticos, eles geralmente são bons em qualquer coisa que exija raciocínio e inteligência. Impulsionados para alcançar a competência em tudo o que fazem, eles podem naturalmente identificar as falhas que venham a existir em uma situação e ver imediatamente como melhorá-las. Eles se esforçam para aperfeiçoar os sistemas em vez de simplesmente aceitá-los como são. Os ENTJs gostam de trabalhar com resolução de problemas complexos e são destemidos em sua busca pelo domínio de qualquer coisa que achem intrigante. Os ENTJs valorizam a verdade acima de tudo e são convencidos apenas pelo raciocínio lógico. Ansiosos para aumentar continuamente sua base de conhecimento, os ENTJs são sistemáticos sobre o planejamento e a pesquisa de coisas novas. Eles estão muito mais interessados ​​nas consequências futuras das ações do que na condição atual das coisas. Líderes naturais com um estilo sincero, os ENTJs tendem a se encarregar das situações em que se encontrem. Eles são bons organizadores de pessoas porque têm a capacidade de ver à frente e depois comunicar sua visão aos outros. Eles tendem a viver de acordo com um conjunto bastante rígido de regras e esperam que os outros também o façam. Portanto, eles tendem a ser aqueles que desafiam os outros a darem o seu melhor e impõe a estes o mesmo esforço que impõe a si mesmos.", author: "Barron & Tieger", f1: "Te", f2: "Ni", f3: "Se", f4: "Fi", f5: "Ti", f6: "Ne", f7: "Si", f8: "Fe", catch: ""}, 
    {name: "INTP", desc: "são solucionadores de problemas conceituais. Eles são intensamente intelectuais e lógicos, com lampejos de brilho criativo. Externamente quietos, reservados e distantes, os INTPs são interiormente absorvidos na análise de problemas. Eles são críticos, precisos e céticos. Eles tentam encontrar e usar princípios para entender suas muitas ideias. Eles gostam que a conversa seja lógica e tenha propósito, mas podem argumentar a ponto de divagar apenas por diversão. INTPs são convencidos apenas pelo raciocínio lógico. Os INTPs geralmente são pensadores engenhosos e originais. Eles valorizam a inteligência em si mesmos, têm um forte impulso pela competência pessoal e estão interessados ​​em desafiar outras pessoas a se tornarem mais competentes também. Os INTPs estão principalmente interessados ​​em ver possibilidades além do que é atualmente conhecido, aceito ou óbvio. Eles gostam de desenvolver modelos para melhorar a forma como as coisas são ou resolver problemas difíceis. Eles pensam de maneiras extremamente complexas e são mais capazes de organizar conceitos e ideias do que pessoas. Ocasionalmente, suas ideias são tão intrincadas que têm dificuldade em se comunicar e fazer com que os outros os compreendam. Altamente independentes, os INTPs desfrutam de atividades especulativas e imaginativas. Eles são flexíveis e de mente aberta e estão mais interessados ​​em encontrar soluções criativas e sólidas para os problemas do que propriamente em ver essas soluções materializadas na realidade.", author: "Barron & Tieger", f1: "Ti", f2: "Ne", f3: "Si", f4: "Fe", f5: "Te", f6: "Ni", f7: "Se", f8: "Fi", catch: ""},
    {name: "INTJ", desc: "são perfeccionistas. Sua forte necessidade de autonomia e boa competência pessoal, bem como sua fé inabalável em suas próprias ideias originais, são seu impulso para alcançar seus objetivos. Lógicos, críticos e engenhosos, os INTJs podem antever as consequências da aplicação de novas ideias e enxergar os sistemas empíricos traduzidos em meios reais. Eles são exigentes consigo mesmos e com os outros, e tendem a lidar com os estes de forma quase tão dura quanto lidam consigo mesmos. Quando em plenitude, não se sentem particularmente incomodados pela indiferença ou crítica. Como os mais independentes de todos os tipos, os INTJs preferem fazer as coisas do seu jeito. Eles geralmente são céticos, definitivos e teimosos diante de forças de oposição. Eles não se impressionam com a autoridade em si, mas podem se conformar às regras apenas se as considerarem úteis para um propósito maior. Com mentes originais, grandes insight e visão, os INTJs são brainstormers naturais. Eles são naturalmente teóricos e funcionam bem com conceitos complexos e globais. Eles são bons pensadores estratégicos e geralmente conseguem ver com clareza os benefícios e as falhas de qualquer situação. Em assuntos que lhes interessam, eles são bons organizadores e tem discernimento. Se a ideia ou projeto é de sua própria autoria, eles podem investir uma incrível concentração, foco, energia e motivação. Suas muitas realizações são alcançadas através da determinação e perseverança para alcançar ou exceder seus altos padrões.", author: "Barron & Tieger", f1: "Ni", f2: "Te", f3: "Fi", f4: "Se", f5: "Ne", f6: "Ti", f7: "Fe", f8: "Si", catch: ""},
    
    {name: "ESTJ", desc: "são ótimos em fazer as coisas acontecerem. Eles gostam de comandar o show e ver as ações sendo destravadas. São responsáveis, conscienciosos e fiéis aos seus compromissos. Eles gostam de estrutura e podem memorizar e organizar muitos detalhes. Eles sistematicamente se empenham em alcançar seus objetivos dentro do cronograma e da forma mais eficiente possível. ESTJs em plenitude são naturalmente inclinados a tomar decisões. Muitas vezes eles baseiam essas decisões em sua própria experiência passada. São lógicos, objetivos, analíticos e possuem grande poder de raciocínio. Na verdade, é improvável que sejam persuadidos por qualquer coisa que não seja lógica. ESTJs são realistas, práticos e concretos. Eles estão mais interessados ​​em \"coisas reais\" do que em intangíveis, como ideias e teorias abstratas. Eles tendem a não se interessar por assuntos para os quais não veem aplicação prática. Eles sabem o que está acontecendo ao seu redor e estão preocupados, em um primeiro momento, com o aqui e agora. Já que vivem de acordo com um certo conjunto de regras, os ESTJs são consistentes e confiáveis. Eles tendem a ser tradicionais e interessados ​​em manter instituições estabelecidas. Eles são consistentes em seus relacionamentos, embora sua vida emocional e social não seja tão importante para eles quanto outros aspectos da vida. Sentem-se à vontade para julgar os outros e podem ser disciplinadores. ESTJs são extrovertidos, sociáveis, diretos e amigáveis. Eles geralmente são fáceis de conhecer, já que com eles \"o que você vê é o que você obtém\".", author: "", f1: "Te", f2: "Si", f3: "Ne", f4: "Fi", f5: "Ti", f6: "Se", f7: "Ni", f8: "Fe", catch: ""},
    {name: "ESFJ", desc: "se sentem motivados a ajudar outras pessoas de maneira real e prática por meio de ações concretas e cooperação. São responsáveis, amigáveis ​​e solidários. Como os ESFJs dão tanta importância aos seus relacionamentos com outras pessoas, eles tendem a ser populares, graciosos, ansiosos por agradar e falantes. Eles precisam de relacionamentos harmoniosos com os outros e trabalham duro para alcançá-los e mantê-los. Na verdade, muitas vezes idealizam o que ou quem admiram. Os ESFJs precisam ser apreciados por si mesmos e por seu serviço, por isso são altamente sensíveis à indiferença ou crítica. Eles geralmente expressam opiniões fortes, são determinados nas situações e gostam de ver as coisas resolvidas. Práticos e realistas, os ESFJs tendem a ser concretos e organizados. Eles atendem e se lembram de fatos e detalhes importantes e gostam que os outros também tenham certeza dos fatos que falam. Eles baseiam seu planejamento e opiniões em sua própria experiência pessoal ou na de outra pessoa em quem confiam. Eles estão cientes e envolvidos com seu ambiente físico e gostam de ser ativos e produtivos. Como os ESFJs são conscienciosos e tradicionais, eles não podem ser separados do seu senso de dever e compromissos. Eles apoiam as instituições estabelecidas e tendem a ser membros ativos e cooperativos de comitês, organizações e partidos políticos. Eles geralmente se esforçam para fazer algo útil e agradável para outra pessoa e, especialmente, gostam de serem responsivos em tempos de problemas ou mesmo em épocas de comemorações.", author: "", f1: "Fe", f2: "Si", f3: "Ne", f4: "Ti", f5: "Fi", f6: "Se", f7: "Ni", f8: "Te", catch: ""},
    {name: "ISTJ", desc: "são os sérios, responsáveis ​​e sensatos \"pilares da sociedade\". Eles são confiáveis ​​e honram seus compromissos. Sua palavra é seu voto solene. Práticos e realistas, os ISTJs são factuais e definitivos. Além disso, são meticulosamente precisos e metódicos, com grandes poderes de concentração. O que quer que estejam fazendo, eles realizam com ordem e confiabilidade. Eles têm ideias inabaláveis ​​e bem pensadas e são difíceis de distrair ou desencorajar uma vez que tenham embarcado no que acreditam ser o melhor curso de ação. Caracteristicamente quietos e trabalhadores, os ISTJs são bons em julgamento prático e tem incrível memória para detalhes. Eles podem citar evidências precisas para apoiar seus pontos de vista e aplicar suas experiências passadas às suas decisões atuais. Eles valorizam e usam a lógica e a análise impessoal, são organizados e sistemáticos em sua abordagem para seguir as coisas e fazê-las no prazo. Eles seguem os sistemas e procedimentos necessários e são impacientes com aqueles que não o fazem. ISTJs são cautelosos e tradicionais. Eles ouvem bem e gostam que as coisas sejam factuais e claramente declaradas. Dizem que \"Diga o que você quer dizer e queira dizer o que você diz\". Privados por natureza, os ISTJs em plenitude parecem calmos mesmo em tempos de crise. Eles são fiéis ao dever e firmes, mas sob sua fachada calma, eles podem ter reações fortes, ainda que raramente expressas.", author: "", f1: "Si", f2: "Te", f3: "Fi", f4: "Ne", f5: "Se", f6: "Ti", f7: "Fe", f8: "Ni", catch: ""},
    {name: "ISFJ", desc: "são leais, dedicados, compassivos e perceptivos sobre como as outras pessoas se sentem. São conscienciosos e responsáveis ​​e gostam de ser necessários. ISFJs são pessoas realistas e \"pés-no-chão\" e preferem estar cercadas majoritariamente de outros quietos e despretensiosos. Eles absorvem, e gostam de usar, um grande número de fatos. Com ótima memória para detalhes, eles costumam ser pacientes na fase de desenvolvimento das tarefas. ISFJs gostam que as coisas sejam expressas de forma clara e explícita. Por terem uma forte ética no trabalho, aceitam a responsabilidade pelas coisas que precisam ser feitas, se puderem enxergar que suas ações realmente ajudarão em alguma coisa. Eles são meticulosamente precisos e sistemáticos no exercício das tarefas. ISFJs tendem a ser conservadores, com valores tradicionais. Eles usam julgamento prático na tomada de decisões e geram estabilidade por meio de sua excelente perspectiva do bom senso. Silenciosos e modestos, os ISFJs são sérios e trabalhadores. Eles são gentis, simpáticos, diplomáticos e apoiam amigos e colegas genuinamente. Eles gostam de cuidar dos outros, preferindo ajudar de maneira prática e tangível. Eles se utilizam do \"calor humano\" para se comunicar e se relacionam bem com as pessoas em necessidade de algo. Os ISFJs tendem a não mostrar seus sentimentos privados, mas têm uma reação pessoal intensa à maioria das situações e eventos. Eles são protetores e dedicados a seus amigos, preocupados com o serviço e comprometidos em cumprir suas obrigações.", author: "", f1: "Si", f2: "Fe", f3: "Ti", f4: "Ne", f5: "Se", f6: "Fi", f7: "Te", f8: "Ni", catch: "– Ações falam mais alto que palavras."},
    
    {name: "ESTP", desc: "\"não se preocupam - eles são felizes!\" Ativos, descontraídos e espontâneos, eles desfrutam do aqui e o agora em detrimento de super-planejar o futuro. Extremamente realistas, os ESTPs confiam no que seus sentidos lhes dizem sobre o mundo. São observadores curiosos e perspicazes. Por aceitarem as coisas como elas são, tendem a ter a mente aberta e a serem tolerantes com os outros e consigo mesmos. ESTPs gostam de coisas reais que podem ser manuseadas, desmontadas e remontadas. Os ESTPs preferem a ação à conversa e gostam de lidar com as situações à medida que elas vão surgindo, sem querer prevê-las por via de regra. Eles são bons solucionadores de problemas porque absorvem informações factuais importantes e necessárias e, por conseguinte, destravam soluções lógicas e sensatas rapidamente, sem muito esforço ou sem desperdiçar energia em excesso. Eles podem agir como negociadores diplomáticos, ficam animados ao tentar abordagens não convencionais para as coisas e geralmente são capazes de persuadir outras pessoas a dar uma chance aos seus métodos práticos. Eles são capazes de compreender os princípios por baixo das coisas e tomar decisões com base no que lhes parece lógico, mais que com base nos seus sentimentos. Portanto, eles são pragmáticos e podem chegar a ser difíceis de lidar quando a situação exige. Amigáveis ​​e charmosos, os ESTPs são populares e se sentem à vontade na maioria das situações sociais. Eles são extrovertidos, versáteis, de jeitão engraçado e podem ter um suprimento vasto de piadas e histórias para várias ocasiões. Eles podem também ser bons em contornar situações tensas, aliviando a atmosfera e aproximando partes conflitantes.", author: "", f1: "Se", f2: "Ti", f3: "Fe", f4: "Ni", f5: "Si", f6: "Te", f7: "Fi", f8: "Ne", catch: ""},
    {name: "ESFP", desc: "gostam de pessoas e têm um verdadeiro entusiasmo pela vida. Eles são brincalhões e vivazes, e tornam as coisas mais divertidas para os outros graças a sua inclinação pura e ousada ao prazer. Adaptáveis ​​e descontraídos, os ESFPs são calorosos, amigáveis ​​e generosos. Eles são extremamente sociáveis ​​e muitas vezes estão \"no palco\" com os outros. Eles participam com entusiasmo e cooperação em atividades e jogos e geralmente fazem \"malabarismos\" com várias atividades ao mesmo tempo. Os ESFPs são observadores realistas que veem e aceitam as coisas como elas são. Eles tendem a confiar no que podem ouvir, cheirar, provar, tocar e ver em vez de explicações teóricas. Como gostam de fatos concretos e têm boa memória para detalhes, aprendem melhor com a experiência prática. Seu bom senso lhes dá habilidades práticas com pessoas e coisas. Eles preferem coletar informações e ver quais soluções surgem naturalmente. Tolerantes e receptivos a si mesmos e aos outros, os ESFPs não tendem a tentar impor sua vontade as outras pessoas. Com tato e simpatia, os ESFPs são, no geral, genuinamente apreciados por muitos. Eles geralmente são capazes de fazer com que os outros adotem suas sugestões, por isso podem ser úteis para ajudar grupos em conflito a voltarem aos trilhos. Eles procuram estar acompanhados de amigos e são bons conversadores. Eles gostam de ajudar as pessoas, mas preferem apoiá-las de maneira real e tangível. Espontâneos e charmosos, os ESFPs são também persuasivos. Eles adoram surpresas e apreciam encontrar maneiras novas de trazer deleite e prazer aos outros.", author:"Barron & Tieger", f1: "Se", f2: "Fi", f3: "Te", f4: "Ni", f5: "Si", f6: "Fe", f7: "Ti", f8: "Ne", catch: "– Ações falam mais alto que palavras."},
    {name: "ISTP", desc: "são pessoas diretas, honestas e pragmáticas que preferem ação à conversa. Eles são despretensiosos e muitas vezes têm uma boa noção de como as coisas funcionam \"internamente\". Por serem analíticos, os ISTPs estão mais interessados ​​nos princípios impessoais e subjacentes das coisas. Os ISTPs têm uma compreensão inata de como as coisas mecânicas funcionam e geralmente são habilidosos no uso de ferramentas e no trabalho com as mãos. Eles tendem a tomar decisões de natureza lógica e privativa, declarando suas ideias e percepções de forma clara e direta, exatamente como as veem. Curiosos e observadores, os ISTPs tendem a ser convencidos apenas por fatos concretos e confiáveis. Eles têm um grande apreço por fatos e podem ser verdadeiros depósitos de informações sobre as coisas que conhecem bem e que entendem. Por serem realistas, conseguem capitalizar bem os recursos disponíveis, o que os torna práticos e com um bom senso de oportunidade. Calados e reservados, os ISTPs tendem a parecer frios e distantes e inclinados à timidez, exceto quando estão com bons amigos. Eles são auto-dirigidos, igualitários e justos. Propensos a agir por impulso, por isso são bastante adaptáveis ​​e reativos frente a desafios e problemas que surgem do nada. Por se darem bem com \"emoção e ação\", eles geralmente gostam de atividades ao ar livre e esportes.", author: "", f1: "Ti", f2: "Se", f3: "Ni", f4: "Fe", f5: "Te", f6: "Si", f7: "Ne", f8: "Fi", catch: ""},
    {name: "ISFP", desc: "são pessoas gentis, atenciosas e sensíveis, que guardam muito de seus ideais e valores pessoais para si mesmos. Eles expressam com mais frequência suas profundas paixões por meio de ações ao invés de palavras. Modestos e mais reservados, os ISFPs são na verdade pessoas extremamente calorosas e entusiasmadas, mas tendem a não mostrar esse lado de si, exceto com pessoas que conhecem bem e confiam. ISFPs tendem a ser incompreendidos por causa de sua tendência a não se expressar diretamente. São pacientes, flexíveis e fáceis de conviver e têm pouca necessidade de dominar ou controlar os outros. Eles não julgam e aceitam o comportamento dos outros de uma maneira bastante prática. Eles são observadores de pessoas e das coisas ao seu redor e não procuram encontrar motivos ou significados. Como os ISFPs vivem principalmente no momento presente, eles não costumam se preparar ou planejar mais do que o mínimo necessário. Bons planejadores de curto prazo, eles se sentem à vontade ao botar a mão na massa porque vivenciam totalmente o aqui e agora. Gostam de aproveitar a experiência atual sem se apressar para a próxima. Interessados ​​no que aprendem e sentem diretamente com as suas experiências e sentidos, muitos acabam por explorar um lado artístico e/ou estético. Procuram também criar ambientes bonitos e personalizados para si mesmos. Sem a necessidade de liderar, os ISFPs geralmente são seguidores leais e bons membros de equipe. Por usarem seus valores pessoais para ajuizarem tudo na vida, eles gostam quando as outras pessoas dedicam algum tempo para conhecê-los e entender suas lealdades internas. Basicamente confiantes e compreensivos, eles precisam de relacionamentos harmoniosos em suas vidas e são sensíveis a conflitos e desacordos.", author: "", f1: "Fi", f2: "Se", f3: "Ni", f4: "Te", f5: "Fe", f6: "Si", f7: "Ne", f8: "Ti", catch: ""},
    
    {name: "ENFJ", desc: "são amantes de pessoas. Eles dão grande importância às pessoas e relacionamentos e são naturalmente preocupados com os outros. Eles adotam uma abordagem calorosa na vida e se sentem conectados pessoalmente à todas as coisas. Por serem idealistas e viverem de acordo com seus valores, os ENFJs são muito leais ao próximo e às causas ou instituições que respeitam e admiram. Eles são normalmente entusiasmados e cheios de energia, bem como responsáveis, conscienciosos e perseverantes. ENFJs têm uma tendência natural a serem, no entanto, autocríticos. Não obstante, por se sentirem responsáveis ​​pelos sentimentos dos outros, os ENFJs raramente são críticos em público. Eles estão cientes do que é (e do que não é) um comportamento apropriado, são graciosos, charmosos, bem-apessoados e adeptos ao meio social. Equilibrados e tolerantes, os ENFJs são diplomáticos e são bons em promover a harmonia ao seu redor. São líderes naturais, populares e carismáticos. Eles tendem a ser bons comunicadores e geralmente usam seu dom expressivo verbalmente. Os ENFJs tomam decisões com base em como se sentem sobre uma situação, em vez de como a situação realmente está ou é. Eles estão interessados ​​nas possibilidades inerentes à alguma coisa, além do que já é óbvio, e nas maneiras como essas possibilidades podem afetar outras pessoas. Sendo naturalmente ordeiros, os ENFJs preferem um mundo organizado e esperam que os outros ajam da mesma forma. Eles gostam de \"resolver as coisas\", mesmo que outra pessoa esteja tomando as decisões. ENFJs irradiam simpatia e compreensão, nutrem e apoiam os outros. Eles lêem bem as pessoas e são responsáveis ​​e atenciosos. Como são idealistas, geralmente enxergam o lado bom nos outros.", author: "", f1: "Fe", f2: "Ni", f3: "Se", f4: "Ti", f5: "Fi", f6: "Ne", f7: "Si", f8: "Te", catch: ""},
    {name: "ENFP", desc: "são cheios de entusiasmo e novas ideias. Otimistas, espontâneos, criativos e confiantes, eles têm mentes originais e um forte senso para possibilidades. Para um ENFP, a vida é uma história emocionante. Por serem assim tão interessados nas possibilidades, os ENFPs veem significância em todas as coisas e preferem manter várias opções abertas. Eles são observadores afiados que percebem qualquer coisa fora do comum. ENFPs ão curiosos e preferem entender em vez de julgar. Imaginativos, adaptáveis ​​e alertas, os ENFPs valorizam a inspiração acima de qualquer coisa e com frequência são inventores hábeis. Por vezes são também inconformistas, tornando-se bons em achar novas maneiras de fazer as coisas. ENFPs abrem novos caminhos para pensamento ou ação... e então os mantém abertos! Ao por em prática suas ideias inovadoras, os ENFPs se apoiam em sua energia impulsiva. Eles têm muita iniciativa e consideram até os problemas estimulantes. Adicionalmente, recebem uma infusão de energia extra quando estão juntos de outras pessoas e podem combinar com sucesso seus talentos com os pontos fortes dos outros. ENFPs são também charmosos e cheios de vitalidade. Eles tratam as pessoas com simpatia, gentileza e cordialidade e estão prontos para ajudar qualquer um com um problema. Eles podem ser nítidamente perspicazes e sensíveis, e frequentemente se preocupam com o desenvolvimento dos outros. Os ENFPs evitam conflitos e preferem a harmonia. Eles despendem mais energia para manter relacionamentos pessoais do que para manter objetos ou coisas, e gostam de que seja uma grande variedade de relacionamentos vivos.", author: "", f1: "Ne", f2: "Fi", f3: "Te", f4: "Si", f5: "Ni", f6: "Fe", f7: "Ti", f8: "Se", catch: ""},
    {name: "INFJ", desc: "habitam num mundo de ideias. São pensadores independentes e originais com sentimentos profundos, princípios firmes e forte integridade pessoal. Os INFJs acreditam em suas próprias ideias e decisões, mesmo diante do ceticismo. Eles são motivados por uma visão interna que valorizam acima de tudo e que pode incluir uma opinião prevalecente ou autoridade estabelecida. Os INFJs geralmente veem significados mais profundos e têm insights intuitivos sobre as situações. Suas inspirações próprias são importantes e válidas para eles, mesmo que outros não compartilhem seu entusiasmo sobre elas. INFJs são leais, comprometidos e idealistas. Se forem, por um lado, quietos, por outro são vigorosos ao tentar fazer suas idéias serem aceitas e aplicadas. Eles valorizam a integridade e podem ser determinados a ponto de serem teimosos. Por causa da força de sua convicção e de sua visão clara do que é melhor para o bem comum, os INFJs podem tornar-se grandes líderes. Eles são geralmente honrados e respeitados por suas contribuições. Como eles valorizam a harmonia e a concordância, os INFJs gostam de persuadir os outros da validade de seu ponto de vista. Eles ganham a cooperação dos outros usando aprovação e elogios como ferramentas, em vez de argumentos ásperos ou intimidação. Os INFJs farão um grande esforço para promover o companheirismo e evitar conflitos. Quase sempre tomadores de decisão ponderados, os INFJs acham os problemas estimulantes e refletem cuidadosamente antes de agir. Eles preferem se concentrar profundamente em uma coisa de cada vez, o que pode resultar em períodos de obstinação. Empáticos e compassivos, os INFJs têm um forte desejo de contribuir para o bem-estar das pessoas de diferentes camadas na comunidade a qual pertencem. Eles estão cientes das emoções e interesses dos outros e geralmente lidam bem com pessoas complicadas. Os próprios INFJs tendem a ter personalidades profundas e complexas e podem tornar-se sensíveis e intensos. Mesmo se forem reservados e difíceis de conhecer, estão dispostos a compartilhar seu eu interior com pessoas em quem confiam. Eles tendem a ter um pequeno círculo de amizades profundas e duradouras e podem gerar muito calor e entusiasmo pessoal nas circunstâncias certas.", author: "", f1: "Ni", f2: "Fe", f3: "Ti", f4: "Se", f5: "Ne", f6: "Fi", f7: "Te", f8: "Si", catch: ""},
    {name: "INFP", desc: "valorizam a harmonia interior acima de tudo. Sensíveis, idealistas e leais, eles têm um forte senso de honra em relação a seus valores pessoais e muitas vezes são motivados por uma profunda crença pessoal, ou pela devoção a uma causa que consideram digna. INFPs estão interessados ​​em possibilidades que vão além do que já é conhecido e concentram a maior parte de sua energia em seus sonhos e visões. De mente aberta, curiosos e perspicazes, eles geralmente têm uma excelente visão de longo alcance. Nos assuntos do dia-a-dia, eles geralmente são flexíveis, tolerantes e adaptáveis, mas são muito firmes em suas lealdades internas e estabelecem padrões muito altos - na verdade, quase impossíveis - para si mesmos. INFPs têm muitos ideais e lealdades que os mantêm ocupados. Eles estão profundamente comprometidos com qualquer coisa de que decidam encarregar-se - e tendem a encarregar-se demais, mas de alguma forma misteriosa fazem tudo. Embora demonstrem uma resiliência fria por fora, os INFPs se preocupam profundamente por dentro. Eles são compassivos, simpáticos, compreensivos e muito sensíveis aos sentimentos dos outros. Eles evitam conflitos e não estão interessados ​​em impressionar ou dominar os outros, a não ser que seus valores estejam em jogo. Muitas vezes, INFPs preferem comunicar seus sentimentos por escrito, em vez de oralmente. Quando eles estão persuadindo os outros da importância de seus ideais, os INFPs podem ser mais convincentes. INFPs raramente expressam a intensidade de seus sentimentos e muitas vezes parecem reticentes e calmos. No entanto, uma vez que eles o conhecem, se mostram entusiasmados e calorosos. INFPs são amigáveis, mas tendem a evitar socialização superficial. Eles valorizam as pessoas que dedicam tempo para compartilhar de seus objetivos e valores.", author: "", f1: "Fi", f2: "Ne", f3: "Si", f4: "Te", f5: "Fe", f6: "Ni", f7: "Se", f8: "Ti", catch: ""},
]

export const as4letrasEnglish = []

export const as4letraspapeis = ["Dominante", "Auxiliar", "Terciária", "Inferior", "Quinta", "Sexta", "Sétima", "Oitava"]

export const as4letraspapeisEnglish = []

export const jungx = [
    {name: "Todos", fullname: "", plural: "", exte: "", desc:"", stickname: ""},
    {name: "Tipo Fe", fullname: "Sentimental Extrovertido", plural: "", exte:"Fe Type - Extraverted Feeling Type", desc:"", stickname: "tipofe"},
    {name: "Tipo Fi", fullname: "Sentimental Introvertido", plural: "", exte:"Fi Type - Introverted Feeling Type", desc:"", stickname: "tipofi"},
    {name: "Tipo Te", fullname: "Pensador Extrovertido", plural: "", exte:"Te Type - Extraverted Thinking Type", desc:"", stickname: "tipote"},
    {name: "Tipo Ti", fullname: "Pensador Introvertido", plural: "", exte:"Ti Type - Introverted Thinking Type", desc:"", stickname: "tipoti"},
    {name: "Tipo Se", fullname: "Sensor Extrovertido", plural: "", exte:"Se Type - Extraverted Sensation Type", desc:"", stickname: "tipose"},
    {name: "Tipo Si", fullname: "Sensor Introvertido", plural: "", exte:"Si Type - Introverted Sensation Type", desc:"", stickname: "tiposi"},
    {name: "Tipo Ne", fullname: "Intuitivo Extrovertido", plural: "", exte:"Ne Type - Extraverted Intuitive Type", desc:"", stickname: "tipone"},
    {name: "Tipo Ni", fullname: "Intuitivo Introvertido", plural: "", exte:"Ni Type - Introverted Intuitive Type", desc:"", stickname: "tiponi"},
]

export const jungEnglish = []



















//Home4LetrasChosen.jsx:
//self:
//todas as linhas/objetos do array de objetos "as4letras" cujo nome é "intj"
//pares de chave-valor especificos do array "as4letraschosen"
//somente os valores, ou seja, as funções cognitivas
//manipulação do array fn para gerar um array de valores das fn na ordem certa
//custom:


/*
  const
    values = ['All', 'Fe', 'Fi', 'Te', 'Ti', 'Se', 'Si', 'Ne', 'Ni'],
    indices = Object.fromEntries(values.map((k, i) => [k, i])),
    given = ['Fe', 'Si', 'Ne', 'Ti', 'Fi', 'Se', 'Ni', 'Te'],
    result = given.map(k => indices[k]);

console.log(...result);

  //for (var i=0; i < as4letraschosenfunctions.length; i++) {}
  console.log(functionsvalues.indexOf("Te", 1))
  1st try:
  let indexchosenfunctionvalues = {}
    originalfunctions.forEach((a, i) => {
      indexchosenfunctionvalues[a] = i;
  })
  let arrayindexchosenfunctionsvalues = as4letraschosenfunctionsvalues.map(x => indexchosenfunctionvalues[x])
  as4letraschosenfunctionsvalues Fe, Si, Ne, Ti, Fi, Se, Ni, Te
  fnx Fe, Fi, Te, Ti, Ne, Ni, Te, Ti
  
  //console.log(as4letraschosen) // Cria um array com |todos os objetos| do array de objetos "as4letras" que passam pelo filtro "nome = ESTJ"
  //console.log(as4letraschosenfunctions) // Cria um array de |objetos e propriedades| retirados do array de objetos "as4letraschosen"
  /* FOR FURTHER APRAISAL
  var data = {"id": 1, "second": "abcd"};

  for(key in data) {
    if(data.hasOwnProperty(key)) {
        var value = data[key];
        console.log(value)
        //do something with value;
    }
  }
  */